movieapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'movieapp'
urlpatterns = [
    # ex: /movieapp/
    url(r'^$', views.IndexView.as_view(), name='index'),
	# ex: /movieapp/signup/
	url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    # ex: /movieapp/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /movieapp/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /movieapp/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

movies/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
	url(r'^movieapp/', include('movieapp.urls')),
    url(r'^admin/', admin.site.urls),
]

movieapp/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User


# Create your models here.
class Question(models.Model):
    # ...
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
		
class Subscriber(models.Model):
	user_rec = models.ForeignKey(User)
	name = models.CharField(max_length=15)
	email = models.CharField(max_length=30)
	join_date = models.DateTimeField('date joined')
	def __str__(self):
		return self.name

movieapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SubscriberForm(UserCreationForm):
    email = forms.EmailField(
        required=True, widget=forms.TextInput(attrs={'class':'form-control'})
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control'})
    )

movieapp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse

from django.urls import reverse
from django.views import generic
from .models import Question

from .forms import SubscriberForm
from django.contrib.auth.models import User

from django.views.generic.base import TemplateView
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class SignUpView(TemplateView):
	template_name = 'signup.html'
	
def subscriber_new(request, template='signup.html'):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            # Unpack form values
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            # Create the User record
            user = User(username=name, email=email)
            user.set_password("password")
            user.save()
            # Create Subscriber Record
            # Process payment (via Stripe)
            # Auto login the user
            return HttpResponseRedirect('/success/')
    else:
        form = SubscriberForm()

    return render(request, template, {'form':form})
	
	
	
	

class DetailView(generic.DetailView):
    model = Question
    template_name = 'detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'results.html'
	
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('movieapp:results', args=(question.id,)))
	

templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
	<head>
        <title>{% block title %}Home {% endblock title %} | CRM Easy</title>
        {% block head_favicon %}
            <link rel="icon" type="image/png"
                  href="{% static 'movieapp/images/favicon.ico' %}">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                <link href="{% static 'movieapp/css/bootstrap.min.css' %}"
                      rel="stylesheet" media="screen">
                <link href="{% static 'movieapp/css/app.css' %}"
                      rel="stylesheet" media="screen">
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
	</head>
	<body>
		{# Navigation Menu #}
		<header>
			<div class="navbar navbar-default navbar-static-top 
			{% block nav-style %}{% endblock %}">
				<div class="container p-none">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle"
								data-toggle="collapse"
								data-target=".navbar-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/movieapp/">Home</a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav navbar-right">
							<li><a href="">Upcoming Movies</a></li>
							<li><a href="">Catalog</a></li>
							<li><a href="">In Theaters</a></li>
							<li><a href="/movieapp/signup/">Sign Up</a></li>							
						</ul>
					</div>
				</div>
			</div>
		</header>
		{# The Document Body #}
		<div id="site-wrapper">
			{% block content %}
				if you see this, something is wrong!
			{% endblock content %}
		</div>
		{# The Footer #}
		<div class="footer">
			<div class="container">
				<p>Contact Us</p>
			</div>
		</div>
	</body>
    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{% static 'movieapp/js/jquery.min.js' %}"></script>
            <script src="{% static 'movieapp/js/bootstrap.min.js' %}"></script>
            <script src="{% static 'movieapp/js/app.js' %}"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>

templates/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'movieapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
</br>
<input type="submit" value="Vote" />
</form>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block nav-style %}mkt-nav{% endblock nav-style %}

{% block content %}  

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img class="center-block" src="{% static 'movieapp/images/split.jpg' %}" alt="Split">
    </div>

    <div class="item">
      <img class="center-block" src="{% static 'movieapp/images/about_time.jpg' %}" alt="About Time">
    </div>

    <div class="item">
      <img class="center-block" src="{% static 'movieapp/images/ex_mach.jpg' %}" alt="Ex-Machina">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{# Main Section #}
<div class="mkt-s2 container">
    <h2 class="mkt-s2-h">Why Buy CRM Easy?</h2>
    <div class="mkt-s2-body">
        <div class="col-md-4 mkt-vp">
            <img class="" src="{% static 'movieapp/images/clock.png' %}"/>
            <h5>Save Time</h5>
            <p>By tracking your customers in
            an easy to use application you'll
            be able to find them faster. Don't
            waste time searching email, looking
            at business cards, or looking online -
            just open CRM Easy!</p>
        </div>
        <div class="col-md-4 mkt-vp">
            <img class="" src="{% static 'movieapp/images/lightbulb.png' %}"/>
            <h5>Stay Current</h5>
            <p>Keeping track of customer details
            is a critical part of serving the customer
            right. Make sure you know what they want and when
            they want it. Use CRM Easy to track all customer
            communications.</p>
        </div>
        <div class="col-md-4 mkt-vp">
            <img class="" src="{% static 'movieapp/images/dollar.png' %}"/>
            <h5>Win Business</h5>
            <p>By tracking customers and staying up
            to date on their requirements you'll be
            in a better position to sell your products
            or services. You win and so does the customer.</p>
        </div>
    </div>
    {# Second Signup Link #}
    <a href="" class=" sgn-btm ">SIGN UP FOR ONLY $15/MONTH</a>
</div>

{% endblock content %}

templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'movieapp:detail' question.id %}">Vote again?</a>

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block nav-style %}mkt-nav{% endblock nav-style %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <form id="user-reg-form" action="." method="post">
                {% csrf_token %}
                {# Username & Password Section #}
                <h3>Signup for weekly newsletters!</h3>
                <h5 class="sn-sh">Enter Name and Email</h5>
                <table class="table">
                    <tbody>
                        <tr>
                            <th>{{ form.name.label }}</th>
                            <th>{{ form.email.label }}</th>
                        </tr>
                        <tr>
                            <td>{{ form.name }}</td>
                            <td>{{ form.email }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.name.errors }}</td>
                            <td>{{ form.email.errors }}</td>
                        </tr>
                    </tbody>
                </table>
                {# Billing Address Section #}
                <input class="btn btn-primary" type="submit" value="submit">
            </form>
            {# Credit Card Section #}
        </div>
    </div>
{% endblock content %}